{
  "openapi": "3.0.0",
  "info": {
    "title": "fhir-openai-plugin",
    "version": "1.0.0"
  },
  "paths": {
    "/fhir/{resourceName}": {
      "get": {
        "operationId": "GetFHIRResource",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "dataModel": {
                      "type": "string"
                    }
                  },
                  "required": ["dataModel"]
                }
              }
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "resourceName",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/fhir/validate": {
      "post": {
        "operationId": "ValidateFHIRResource",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "validatorOutput": {
                      "type": "string"
                    }
                  },
                  "required": ["validatorOutput"]
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "resourceJson": {
                    "type": "object"
                  }
                },
                "required": ["resourceJson"]
              }
            }
          }
        }
      }
    }
  }
}
